import emoji

# Emoji used in bot interface
EMJ_OLD_TELEPHONE = emoji.emojize(  ':telephone:'             , use_aliases=True)
EMJ_WRITING_HAND  = emoji.emojize(  ':writing_hand:'          , use_aliases=True)
EMJ_RAISING_HAND  = emoji.emojize(  ':person_raising_hand:'   , use_aliases=True)
EMJ_EXCLAMATION   = emoji.emojize(  ':red_exclamation_mark:'  , use_aliases=True)
EMJ_BACK_ARROW    = emoji.emojize(  ':BACK_arrow:'            , use_aliases=True)
EMJ_MONEY_BAG     = emoji.emojize(  ':money_bag:'             , use_aliases=True)
EMJ_RECYCLING     = emoji.emojize(  ':recycling_symbol:'      , use_aliases=True)
EMJ_TELEPHONE     = emoji.emojize(  ':telephone_receiver:'    , use_aliases=True)
EMJ_QUESTION      = emoji.emojize(  ':white_question_mark:'   , use_aliases=True)
EMJ_DOCTOR        = emoji.emojize(  ':man_health_worker:'     , use_aliases=True)
EMJ_GLOBE         = emoji.emojize(  ':globe_with_meridians:'  , use_aliases=True)
EMJ_CROSS         = emoji.emojize(  ':cross_mark:'            , use_aliases=True)
EMJ_HOUSE         = emoji.emojize(  ':house:'                 , use_aliases=True)
EMJ_PLUS          = emoji.emojize(  ':plus:'                  , use_aliases=True)
EMJ_NOTE          = emoji.emojize(  ':memo:'                  , use_aliases=True)
EMJ_INFO          = emoji.emojize(  ':information:'           , use_aliases=True)
EMJ_DISK          = emoji.emojize(  ':computer_disk:'         , use_aliases=True)
EMJ_DONE          = emoji.emojize(  ':check_mark_button:'     , use_aliases=True)