import emoji

# Emoji used in bot interface
EMJ_OLD_TELEPHONE = emoji.emojize(':telephone:'           )
EMJ_WRITING_HAND  = emoji.emojize(':writing_hand:'        )
EMJ_RAISING_HAND  = emoji.emojize(':person_raising_hand:' )
EMJ_EXCLAMATION   = emoji.emojize(':red_exclamation_mark:')
EMJ_BACK_ARROW    = emoji.emojize(':BACK_arrow:'          )
EMJ_MONEY_BAG     = emoji.emojize(':money_bag:'           )
EMJ_RECYCLING     = emoji.emojize(':recycling_symbol:'    )
EMJ_TELEPHONE     = emoji.emojize(':telephone_receiver:'  )
EMJ_QUESTION      = emoji.emojize(':white_question_mark:' )
EMJ_DOCTOR        = emoji.emojize(':man_health_worker:'   )
EMJ_GLOBE         = emoji.emojize(':globe_with_meridians:')
EMJ_CROSS         = emoji.emojize(':cross_mark:'          )
EMJ_HOUSE         = emoji.emojize(':house:'               )
EMJ_PLUS          = emoji.emojize(':plus:'                )
EMJ_NOTE          = emoji.emojize(':memo:'                )
EMJ_INFO          = emoji.emojize(':information:'         )
EMJ_DISK          = emoji.emojize(':computer_disk:'       )
EMJ_DONE          = emoji.emojize(':check_mark_button:'   )